# Generated by Django 6.0.6 on 2026-06-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(default='Untitled Blog', max_length=100),
            preserve_default=False,
        ),
    ]
